### PR TITLE
purchase order class

### PR DESCRIPTION
**Pull request by xstunes**
purchase order class, added generate order, update, delete.
working on price and status update.

### CODE REVIEW

**Comment by xstunes** [comment]
removed requisition extend, add scanner for input purchase order details, update status.

**Review by j0eTheRipper — CHANGES_REQUESTED** [review]
Follow the diagram sent on whatsapp

**Comment by xstunes** [comment]
done, pls check.

**Review by j0eTheRipper — APPROVED** [review]
merging...

**Pull request merged**
